package vehicle.maintenance.tracker;

import java.util.List;

/**
 * Vehicle represents a tracked entity within the database 
 * we can use to schedule maintenance.
 *
 * @author add your name
 * @author Daile Alimo
 * @since 0.1-SNAPSHOT
 */
public class Vehicle {

    private int id;
    private int mileage;
    private String registration;

    // this constructor is for database loaded Vehicles.
    public Vehicle(int id, int mileage, String registration){
	this.id = id;
	this.mileage = mileage;
	this.registration = registration;
    }

    // id will be auto generated by database.
    // so we will use this constructor when we instantiate.
    public Vehicle(int mileage, String registration){
	this.mileage = mileage;
	this.registration = registration;
    }

    public int getMileage() {
        return this.mileage;
    }

    public int getId() {
        return this.id;
    }

    public String getRegistration() {
        return this.registration;
    }

}
